-- V10: Seed CMS data - services and service packages
INSERT INTO cms.services (uuid, name, category, description, duration_minutes, price, rating, active, included_items, required_documents) VALUES
(gen_random_uuid(), 'Basic Nursing Care', 'NURSING_CARE', 'Wound dressing, medication administration, vital signs monitoring, insulin injections', 60, 45.00, 0, true, ARRAY['Nursing assessment', 'Care plan'], ARRAY['Health insurance card']),
(gen_random_uuid(), 'Post-Operative Care', 'POST_SURGERY_CARE', 'Specialized post-surgical care including wound management, drain care, and mobilization support', 90, 65.00, 0, true, ARRAY['Post-op assessment', 'Wound care', 'Pain monitoring'], ARRAY['Health insurance card', 'Doctor referral']),
(gen_random_uuid(), 'Wound Care Treatment', 'WOUND_CARE', 'Professional wound assessment and treatment for acute and chronic wounds', 60, 55.00, 0, true, ARRAY['Wound assessment', 'Dressing change', 'Care plan'], ARRAY['Health insurance card']),
(gen_random_uuid(), 'Physiotherapy Session', 'PHYSIOTHERAPY', 'Assessment and treatment of musculoskeletal conditions, pain management, and rehabilitation exercises', 60, 55.00, 0, true, ARRAY['Initial assessment', 'Treatment plan'], ARRAY['Health insurance card']),
(gen_random_uuid(), 'Elderly Care', 'ELDERLY_CARE', 'Comprehensive care for elderly patients including mobility assistance and daily living support', 120, 70.00, 0, true, ARRAY['Mobility assistance', 'Daily living support', 'Medication reminders'], ARRAY['Health insurance card']),
(gen_random_uuid(), 'Chronic Disease Monitoring', 'CHRONIC_DISEASE_MONITORING', 'Ongoing monitoring and management of chronic conditions like diabetes, hypertension, and heart disease', 45, 50.00, 0, true, ARRAY['Health assessment', 'Medication review', 'Monitoring logs'], ARRAY['Health insurance card', 'Medical history']),
(gen_random_uuid(), 'Palliative Care', 'PALLIATIVE_CARE', 'Specialized comfort care for patients with serious illnesses focusing on quality of life', 90, 80.00, 0, true, ARRAY['Pain management', 'Symptom control', 'Emotional support'], ARRAY['Health insurance card', 'Doctor referral']),
(gen_random_uuid(), 'Pediatric Care', 'PEDIATRIC_CARE', 'Specialized home healthcare for children by qualified pediatric nurses', 60, 60.00, 0, true, ARRAY['Child health assessment', 'Developmental monitoring', 'Parental guidance'], ARRAY['Health insurance card', 'Pediatrician referral']),
(gen_random_uuid(), 'Medical Consultation', 'MEDICAL_CONSULTATION', 'Doctor visit for diagnosis, treatment planning, and medical oversight', 45, 70.00, 0, true, ARRAY['Medical history review', 'Physical examination', 'Treatment plan'], ARRAY['Health insurance card']),
(gen_random_uuid(), 'Laboratory Services', 'LABORATORY_SERVICES', 'Blood draws and sample collection for laboratory analysis in the comfort of home', 15, 15.00, 0, true, ARRAY['Blood draw', 'Sample labeling', 'Lab referral processing'], ARRAY['Health insurance card', 'Lab referral']);

INSERT INTO cms.service_packages (name, size, description, service_ids, price, discount_percent, validity_days, benefits, active) VALUES
('Basic Care Package', 'S', 'Ideal for patients requiring regular but simple care interventions', ARRAY[1]::BIGINT[], 400.00, 10, 30, ARRAY['4 basic nursing visits', 'Priority scheduling', 'Phone consultation'], true),
('Recovery Plus Package', 'M', 'Comprehensive post-procedure or post-hospitalization care', ARRAY[2, 4, 10]::BIGINT[], 550.00, 15, 60, ARRAY['6 nursing visits', '2 physio sessions', 'Lab tests included', 'Care coordination'], true),
('Comprehensive Care Package', 'L', 'Full-service ongoing care for patients with complex or chronic needs', ARRAY[9, 1, 4, 6]::BIGINT[], 1200.00, 20, 90, ARRAY['8 nursing visits', '4 physio sessions', '2 doctor visits', 'Unlimited phone support', 'Priority scheduling'], true);
